name: Sync Fork

on:
  schedule:
    - cron: '0 8 */7 * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: soreatu
          base: master
          head: master
